package com.aplus.pillreminder.model;

public class StaticData {
    public static final String[] PILL_NAMES = new String[] {
            "Abacavir", "เอบาคาเวียร์",
            "Acebutolol", "อะซีบูโทลอล",
            "Adapalene", "เอดาพาลีน",
            "Albendazole", "อัลเบนดาโซล",
            "Allopurinol", "อัลโลพูรินอล",
            "Altretamine", "แอลเทรทามีน",
            "Aluminum hydroxide", "อะลูมินัมไฮดรอกไซด์",
            "Amcinonide", "แอมซิโนไนด์ชนิดใช้กับผิวหนัง",
            "Amiloride", "อะมิโลไรด์",
            "Amoxicillin", "อะมอกซิซิลลิน",
            "Ampicillin", "แอมพิซิลลิน",
            "Amprenavir", "แอมพรีนาเวียร์",
            "Anastrozole", "อนาสโทรโซล",
            "Arsenic trioxide", "อาร์เซนิค ไทรออกไซด์",
            "Asparaginase", "แอสพาราจิเนส",
            "Aspirin", "แอสไพริน",
            "Atenolol", "อะทีโนลอล",
            "Azacitidine", "แอซาไซทิดีน",
            "Azithromycin", "อะซิโทรมัยซิน",
            "Baclofen", "แบโคลเฟน",
            "Beclomethasone dipropionate", "เบโคลเมทาโซนไดโพรพิโอเนต",
            "Benzoyl Peroxide", "เบนโซอิลเพอรอกไซด์",
            "Betamethasone", "เบทาเมทาโซน",
            "Bismuth subsalicylate", "บิสมัทซับซาลิซิเลต",
            "Bisoprolol", "บิโซโพลอล",
            "Bleomycin", "บลีโอมัยซิน",
            "Brompheniramine", "บรอมเฟนิรามีน",
            "Budesonide", "บูเดโซไนด์",
            "Busulfan", "บิวซัลแฟน",
            "Calcium acetate", "แคลเซียมแอซีเทต",
            "Calcium carbonate", "แคลเซียมคาร์บอเนต",
            "Calcium gluconate", "แคลเซียมกลูโกเนต",
            "Calcium lactate", "แคลเซียมแลคเทต",
            "Captopril", "แคปโทพริล",
            "Cefaclor", "เซฟาคลอร์",
            "Cefadroxil", "เซฟาดรอกซิล",
            "Cefdinir", "เซฟดิเนียร์",
            "Cefditoren", "เซฟดิทอเรน",
            "Cefixime", "ซีฟิกซีม",
            "Cefpodoxime", "เซฟโพดอกซีม",
            "Cefprozil", "เซฟโพรซิล",
            "Ceftibuten", "เซฟทิบิวเท็น",
            "Cefuroxime", "เซฟิวรอกซีม",
            "Celecoxib", "เซเลโคซิบ",
            "Cephalexin", "เซฟาเลกซิน",
            "Cetirizine", "ซีเทอริซีน",
            "Chloramphenicol", "คลอแรมเฟนิคอล",
            "Chlorpheniramine", "คลอเฟนิรามีน",
            "Chlortetracycline", "คลอร์เททราซัยคลิน",
            "Chlorzoxazone", "คลอร์ซ็อกซาโซน",
            "Cimetidine", "ไซเมทิดีน",
            "Ciprofloxacin", "ซิโพรฟลอกซาซิน",
            "Clarithromycin", "ชลาริโทรมัยซิน",
            "Clindamycin", "คลินดาไมซิน",
            "Clotrimazole", "โคลทริมาโซล",
            "Cloxacillin", "คลอกซาซิลลิน",
            "Colchicine", "คอลชิซีน",
            "Desloratadine", "เดสลอแรทาดีน",
            "Dextromethorphan", "เดกซ์โทรเมทอร์แฟน",
            "Diclofenac", "ไดโคลฟีแนก",
            "Dicloxacillin", "ไดคลอกซาซิลลิน",
            "Diflunisal", "ไดฟลูนิซัล",
            "Diltiazem", "ดิลไทอาเซม",
            "Dimenhydrinate", "ไดเมนไฮดริเนท",
            "Diphenhydramine", "ไดเฟนไฮดรามีน",
            "Doxycycline", "ดอกซีซัยคลิน",
            "Enalapril", "อีแนลาพริล",
            "Erythromycin", "อีริโทรมัยซิน",
            "Famotidine", "แฟโมทิดีน",
            "Felodipine", "ฟีโลดิพีน",
            "Ferric ammonium citrate", "เฟอร์ริกแอมโมเนียมซิเทรต",
            "Ferrous fumarate", "เฟอร์รัสฟูมาเรต",
            "Ferrous sulfate", "เฟอร์รัสซัลเฟต",
            "Fexofenadine", "เฟกโซฟีนาดีน",
            "Fluconazole", "ฟลูโคนาโซล",
            "Fludarabine", "ฟลูดาราบีน",
            "Fludrocortisone", "ฟลูโดรคอร์ติโซน",
            "Flunarizine", "ฟลูนาริซีน",
            "Flurbiprofen", "เฟลอบิโพรเฟน",
            "Furosemide", "ฟูโรซีไมด์",
            "Fusidic acid", "กรดฟิวซิดิก",
            "Gatifloxacin", "กาติฟลอกซาซิน",
            "Gentamicin", "เจนทาไมซิน",
            "Guaifenesin", "ไกวเฟนิซิน",
            "Hydrochlorothiazide", "ไฮโดรคลอโรไทอาไซด์",
            "Hydroxyzine", "ไฮดรอกซิซีน",
            "Ibuprofen", "ไอบิวโพรเฟน",
            "Indomethacin", "อินโดเมทาซิน",
            "Isotretinoin", "ไอโซเทรทิโนอิน",
            "Itraconazole", "อิทราโคนาโซล",
            "Ketoconazole", "คีโทโคนาโซล",
            "Ketoprofen", "คีโทโพรเฟน",
            "Labetalol", "ลาบิทาลอล",
            "Lamivudine", "ลามิวูดีน",
            "Lansoprazole", "แลนโซพราโซล",
            "Letrozole", "เลโทรโซล",
            "Levofloxacin", "ลีโวฟลอกซาซิน",
            "Lomefloxacin", "โลมีฟลอกซาซิน",
            "Loperamide", "โลเพอราไมด์",
            "Lopinavir+ritonavir", "ยาเม็ดรวมโลพินาเวียร์และริโทนาเวียร",
            "Loratadine", "ลอแรทาดีน",
            "Losartan", "โลซาร์แทน",
            "Magnesium oxide", "แมกนีเซียมออกไซด์",
            "Mebendazole", "มีเบนดาโซล",
            "Mefenamic acid", "กรดมีฟีนามิค",
            "Meloxicam", "มีล็อกซิแคม",
            "Melphalan", "เมลฟาแลน",
            "Mesna", "เมสนา",
            "Methotrexate", "เมโทเทรกเซต",
            "Methyltestosterone", "เมทิลเทสโทสเตอโรน",
            "Metoclopramide", "เมโทโคลพราไมด์",
            "Metoprolol", "เมโทโพรลอล",
            "Metronidazole", "เมโทรนิดาโซล",
            "Minocycline", "มิโนซัยคลิน",
            "Mitomycin", "ไมโทมัยซิน",
            "Mitoxantrone", "ไมโทแซนโทรน",
            "Moxifloxacin", "โมซิฟลอกซาซิน",
            "Nabumetone", "นาบูมีโทน",
            "Nalidixic acid", "กรดนาลิดิซิก",
            "Naproxen", "นาพรอกเซน",
            "Neomycin", "นีโอมัยซิน",
            "Nimesulide", "ไนมีซูไลด์",
            "Nitrofurantoin", "ไนโทรฟิวแรนทอยน์",
            "Nizatidine", "ไนซาทิดีน",
            "Norfloxacin", "นอร์ฟลอกซาซิน",
            "Nystatin",  "ไนสแททิน",
            "Ofloxacin", "โอฟลอกซาซิน",
            "Olmesartan", "ออมีซาร์แทน",
            "Omeprazole", "โอเมพราโซล",
            "Orphenadrine", "ออร์เฟนนาดรีน",
            "Paclitaxel", "แพคลิแทกเซล",
            "Pantoprazole", "แพนโทพราโซล",
            "Paracetamol", "พาราเซทามอล",
            "Pemetrexed", "เพมิเทรกเซด",
            "Perindopril", "เพอรินโดพริล",
            "Phenylbutazone", "ฟีนิลบิวทาโซน",
            "Piroxicam", "เพียร็อกซิแคม",
            "Prednisolone", "เพรดนิโซโลน",
            "Probenecid", "โพรเบนีซิด",
            "Propranolol", "โพรแพโนนอล",
            "Oxaliplatin", "ออกซาลิแพลทิน",
            "Oxytetracycline", "ออกซีเททราซัยคลิน",
            "Quinapril", "ควินาพริล",
            "Rabeprazole", "ราบีพราโซล",
            "Ramipril", "รามิพริล",
            "Ranitidine", "รานิทิดีน",
            "Roxithromycin", "รอกซิโทรมัยซิน",
            "Saquinavir", "ซาควินาเวียร์",
            "Simethicone", "ซิเมทิโคน",
            "Sodium salicylate", "โซเดียมซาลิซิเลต",
            "Sotalol", "โซทาลอล",
            "Spironolactone", "สไพโรโนแลกโทน",
            "Sucralfate", "ซูคราลเฟต",
            "Sulfadiazine", "ซัลฟาไดอาซีน",
            "Sulfadimidine", "ซัลฟาไดมิดีน",
            "Sulfasalazine", "ซัลฟาซาลาซีน",
            "Sulindac", "ซูลินแดค",
            "Sultamicillin", "ซัลทามิซิลลิน",
            "Valsartan", "วาลซาร์แทน",
            "Verapamil", "วีราพามิล",
            "Vinblastine", "วินบลาสทีน",
            "Vincristine", "วินคริสทีน",
            "Vinorelbine", "วินนอร์เรลบีน",
            "Zidovudine", "ไซโดวูดีน"
    };
}
